### PR TITLE
Fixes Assertion issue in Selftest code for url.NetLocation="localhost".

### PR DESCRIPTION
**Pull request by tempelmann**

### CODE REVIEW

**Comment by tempelmann** [comment]
Please someone merge this - I can't do it myself.

**Comment by vidalvanbergen** [comment]
I'm not sure declaresub is subscribed to notifications of pull requests, you may have to contact him directly.

**Comment by jda1** [comment]
Shouldn't changes be made to the new 64-bit MacOSLib? The 32-bit library obsolete.

**Comment by vidalvanbergen** [comment]
The 64-bit version of macoslib is still in its experimental stages, I've pulled the changes into both branches.

**Comment by jda1** [comment]
Great. Maybe that should be renamed to MacOSLib 2, or MacOSLib 64, to avoid confusion? Also, I have fixed a bug in MacOSLib I'd like to send along to you (I'm not comfortable making changes in GitHub). How can I do that?

**Comment by vidalvanbergen** [comment]
It's preferable if you do use github to fork this project (or mine), make some changes and commit them back to github.
If you don't want to use a github repository, maybe you can try opening a new issue describing the changes you made to which files? and possibly attach them to the message.

**Comment by jda1** [comment]
It's not much. In NSURL.ResourceValue,

  dim OK as Boolean = setResourceValue(newValue.id, newValue, forKey, err )

should be

  dim OK as Boolean = setResourceValue(self, newValue, forKey, err )

Ironically, this is a fix you suggested yourself in 2014, but didn't appear to make it into the main build. See this thread

https://github.com/macoslib/macoslib/issues/152

**Comment by tempelmann** [comment]
Huh, I had no realized that my pushes yesterday would still be on the list to be added to the master. I thought I only pushed them to my fork.
In my own fork, I think it's okay to have that personal .rbp version

**Comment by tempelmann** [comment]
Or is there still someone around who can merge changes into the 32 bit master version?

**Comment by vidalvanbergen** [comment]
That certainly was long ago, high time I finally did something about it. :)

Unfortunately the original project seems to be unmaintained, however I've been pulling new commits into my own fork to keep things going. I've already pulled your latest changes (Minus the personal project file) into both my 32-bit branch, and a slightly modified one into the 64-bit branch.

So far the changes seem to keep the project running, but i'm not sure how to test if 64-bit version has been modified correctly. (Changed UInt32 references to UInteger)

**Comment by tempelmann** [comment]
As I keep using the old IDE (2012r2.1) for editing my projects, I cannot use UInteger nor CGFloat in my projects, so my version of macoslib will probably remain different in this regard. That's why I have that rbp file. I have a 64 bit version of the SmartPrefs, but it seems someone else had already fixed them anyway?

**Comment by vidalvanbergen** [comment]
The 64-bit branch's smartprefs seem to be working correctly, though I added variant.TypeInt64 to integer recognition under TTsSmartPreferences.toCFType as a previously saved integer value in one of my projects didn't get properly recognised anymore.
You can find the 64 bit version here, and see for yourself how the implementation's been done:
https://github.com/vidalvanbergen/macoslib/tree/master-64bit.
And maybe clone it and make some commits to it yourself if you see fit to make some changes to it. ;)

You could keep the private file in a new 'private use' branch of your project, or outside of the macoslib folder.

**Pull request closed without merging**
