### PR TITLE
IoKit: Added IdleTime method

### PR DESCRIPTION
**Pull request by jcowgar**
Returns the number of nanoseconds the user has been idle. The method and an example window have been added. This is the first time I have contributed to macoslib and the first time I have done any OS X specific external method work, so before merging it would be nice to have an experienced macoslib developer double check the work in IoKit.IdleTime.

Thanks!

### CODE REVIEW

**Comment by vidalvanbergen** [comment]
It works as described. ;)
Make sure to add your name to contributors and a release note to the 'About' module.

**Comment by jcowgar** [comment]
Do I actually increment the version number for this one change?

**Comment by vidalvanbergen** [comment]
yup, any change is a change.

**Comment by jcowgar** [comment]
Done

**Comment by vidalvanbergen** [comment]
Good, now wait till @declaresub notices this pull request and see what he thinks of it. ;)

**Comment by declaresub** [comment]
> On Jun 21, 2015, at 3:47 PM, Vidal van Bergen <notifications@github.com> wrote:
> 
> Good, now wait till @declaresub notices this pull request and see what he thinks of it. ;)
> 

You define 

+		  dim idleNanoSecs as Int64 = -1

which I suppose is intended to be a magic error value.  But later you define


+		          dim defaultNanosecs as new CFNumber(0)

So does this mean that there are now two magic error values?


+		          dim obj as CFNumber = CFNumber(dict.Lookup(new CFString(kHIDIdleTime), defaultNanosecs))
+		          if obj isa CFNumber then
+		            idleNanoSecs = obj.Int64Value
+		          end if


obj isa CFNumber will always evaluate to true unless obj is nil.  So it makes more sense to me to test for that.


And there is a lot of fall-through error handling, which I dislike because it makes the code harder to follow, and often leads to programming errors.

I see a semantic distinction between “if statements” and “if expressions”.  In general, if expressions really should have an else clause to make the alternative behavior explicit.

**Comment by jcowgar** [comment]
You're right, I fixed the duplicate error code. I also didn't like the nested if's. I was porting some Obj-C code to produce this. To prevent the nested if's should I be raising macoslibExceptions when an error condition occurs?

Simply adding else statements would mean to handle it I'd have to return early, which a lot of people don't care for either.

**Comment by declaresub** [comment]
Well, a lot of people don't like exceptions either.  I don't mind early returns when their purpose is clear; in particular, as guard clauses.

I should also note that you get bonus points for including an example window.  The new version of macoslib includes unit test support, but a lot of functionality is probably best tested in examples.

**Comment by jcowgar** [comment]
OK, I think that should have it

**Pull request merged**
